site_name: Emad's Blog
theme:
  name: material
  palette:
    scheme: default
    primary: white


extra_css:
  - stylesheets/footer.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
